services:
  
  backend:
    build: ./Backend
    environment:
      - DATABASE_URL="postgresql://postgres:123@postgres:5432/chatapp"
      - PORT=3000
      - JWT_SECRET=123
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chatapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

volumes:
  postgres_data:
  prometheus_data: