services:
  
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ./Backend/.env
  
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./Backend/.env
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./Backend/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

volumes:
  postgres_data:
  prometheus_data: